create extension if not exists pgcrypto;

create table if not exists public.restaurant_menus (
  id uuid primary key default gen_random_uuid(),
  restaurant_name text not null,
  location text,
  cuisine text,
  average_check_min_chf numeric(10, 2),
  average_check_max_chf numeric(10, 2),
  menu_category text not null,
  item_name text not null,
  description text,
  price_chf numeric(10, 2),
  price_text text,
  dietary_tags text,
  source_url text,
  source_updated_at date,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint restaurant_menus_unique_item unique (
    restaurant_name,
    menu_category,
    item_name
  )
);

create index if not exists restaurant_menus_active_restaurant_idx
  on public.restaurant_menus(is_active, restaurant_name);

create index if not exists restaurant_menus_category_idx
  on public.restaurant_menus(menu_category);

with rows(
  restaurant_name,
  location,
  cuisine,
  average_check_min_chf,
  average_check_max_chf,
  menu_category,
  item_name,
  description,
  price_chf,
  price_text,
  dietary_tags,
  source_url,
  source_updated_at
) as (
  values
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'average_check',
      'Average check',
      'Typical lunch estimate based on the published menu: simple dishes and children meals are lower; most adult mains are around CHF 21-38; tartar and Hannigplatte are higher.',
      null::numeric,
      'Approx. CHF 35-55 per adult for a main dish plus a drink or small starter',
      null,
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'salads',
      'Grüner Alpensalat',
      'Green salad.',
      11,
      'CHF 11',
      'vegetarian',
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'salads',
      'Gemischtes aus dem Garten',
      'Mixed salad.',
      13,
      'CHF 13',
      'vegetarian',
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'salads',
      'Hannigsalat',
      'Melon and arugula salad with marinated lamb strips and honey-mustard dressing.',
      26,
      'CHF 26',
      null,
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'soups',
      'Alpenkräuter Heusuppe mit Apfel',
      'Alpine herb hay soup with apple.',
      11,
      'CHF 11',
      'vegetarian',
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'soups',
      'Traditionelle Saaser Fleischsuppe',
      'Homemade broth with bread, potatoes and cheese.',
      16,
      'CHF 16',
      null,
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'soups',
      'Rindskraftbrühe',
      'Beef bouillon.',
      9,
      'CHF 9',
      null,
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'zvieri',
      'Saaser Teller',
      'Air-cured meat, sliced cheese, Saas sausage, cured ham and bacon.',
      33,
      'CHF 33; half portion CHF 23',
      null,
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'zvieri',
      'Trockenfleisch Teller',
      'Air-cured meat platter.',
      null::numeric,
      'Half portion CHF 23; full price not listed in extracted menu text',
      null,
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'zvieri',
      'Hobelkäse Teller',
      'Plate of chipped cheese.',
      29,
      'CHF 29; half portion CHF 21',
      'vegetarian',
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'sides',
      'Portion Pommes',
      'Portion of french fries.',
      13,
      'CHF 13',
      'vegetarian',
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'children',
      'Murmeli',
      'Children portion of french fries.',
      8,
      'CHF 8',
      'vegetarian',
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'children',
      'Zwärgi',
      'Children Älplermacronen / cheese macaroni.',
      13,
      'CHF 13',
      'vegetarian',
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'children',
      'Rehteller',
      'Chicken nuggets with french fries.',
      15,
      'CHF 15',
      null,
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'children',
      'Hirschteller',
      'Spaghetti with tomato sauce.',
      11,
      'CHF 11',
      'vegetarian',
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'roesti',
      'Alpen-Rösti',
      'Rösti with egg and small green salad garnish.',
      24,
      'CHF 24',
      'vegetarian',
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'roesti',
      'Hirten-Rösti',
      'Rösti with carrots, onions, dill, arugula and Belper Knolle cheese.',
      26,
      'CHF 26',
      'vegetarian',
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'roesti',
      'Bauern-Rösti',
      'Farmhouse sausage with rösti and onion sauce.',
      25,
      'CHF 25',
      null,
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'roesti',
      'Stroganoff-Rösti',
      'Sliced beef with fine Stroganoff sauce.',
      37,
      'CHF 37',
      null,
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'roesti',
      'Nordmann-Rösti',
      'Rösti with house-smoked salmon and sour cream.',
      27,
      'CHF 27',
      null,
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'cheese_specialties',
      'Schmugglerschnitta',
      'Cheese toast with wine.',
      22,
      'CHF 22',
      'vegetarian',
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'cheese_specialties',
      'Älplermakaroni',
      'Macaroni with cheese, potatoes, onions and apple compote.',
      24,
      'CHF 24',
      'vegetarian',
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'cheese_specialties',
      'Glaffni Spaghetti',
      'Spaghetti boiled in white wine with cheese sauce and Saas sausage.',
      21,
      'CHF 21',
      null,
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'cheese_specialties',
      'Käsefondue',
      'Cheese fondue.',
      29,
      'CHF 29',
      'vegetarian',
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'cheese_specialties',
      'Käsefondue mit Champagner und Trüffel',
      'Cheese fondue with champagne and truffles.',
      38,
      'CHF 38',
      'vegetarian',
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'cheese_specialties',
      'Käsefondue mit Champagner und Safran',
      'Cheese fondue with champagne and saffron.',
      35,
      'CHF 35',
      'vegetarian',
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'house_specialties',
      'Silvio''s Tartar',
      'Beef tartare with fermented garlic mayonnaise, Belper Knolle and toast.',
      45,
      'CHF 45; half portion CHF 29; add french fries CHF 6',
      null,
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'house_specialties',
      'Z''vegi Tartar',
      'Dried tomato tartare with herb oil and toast.',
      35,
      'CHF 35; add french fries CHF 6',
      'vegetarian',
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'house_specialties',
      'Cordon Bleu Hannig',
      'Pork schnitzel filled with ham and saffron raclette cheese, served with vegetables and french fries.',
      35,
      'CHF 35; fitness plate with salad only CHF 29',
      null,
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    ),
    (
      'Hannig',
      'Hannigweg 40, 3906 Saas-Fee',
      'Mountain restaurant, Swiss/alpine',
      35,
      55,
      'chef_recommends',
      'Hannigplatte',
      'From 2 persons: finely sliced beef entrecote with Café de Paris sauce and seasonal vegetables.',
      48,
      'CHF 48 per person; french fries CHF 6; homemade almond croquettes CHF 7',
      null,
      'https://www.bergrestaurant-hannig.ch/speisekarte',
      '2026-06-11'::date
    )
)
insert into public.restaurant_menus (
  restaurant_name,
  location,
  cuisine,
  average_check_min_chf,
  average_check_max_chf,
  menu_category,
  item_name,
  description,
  price_chf,
  price_text,
  dietary_tags,
  source_url,
  source_updated_at,
  is_active,
  updated_at
)
select
  restaurant_name,
  location,
  cuisine,
  average_check_min_chf,
  average_check_max_chf,
  menu_category,
  item_name,
  description,
  price_chf,
  price_text,
  dietary_tags,
  source_url,
  source_updated_at,
  true,
  now()
from rows
on conflict (restaurant_name, menu_category, item_name) do update set
  location = excluded.location,
  cuisine = excluded.cuisine,
  average_check_min_chf = excluded.average_check_min_chf,
  average_check_max_chf = excluded.average_check_max_chf,
  description = excluded.description,
  price_chf = excluded.price_chf,
  price_text = excluded.price_text,
  dietary_tags = excluded.dietary_tags,
  source_url = excluded.source_url,
  source_updated_at = excluded.source_updated_at,
  is_active = true,
  updated_at = now();
