create extension if not exists pgcrypto;

create table if not exists public.local_events (
  id uuid primary key default gen_random_uuid(),
  source_key text not null unique,
  location text not null,
  category text not null default 'event',
  title text not null,
  start_date date not null,
  end_date date,
  time_text text,
  venue text,
  description text not null,
  price text,
  registration text,
  source_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists local_events_active_dates_idx
  on public.local_events(is_active, start_date, end_date);

create index if not exists local_events_location_idx
  on public.local_events(location);

with rows(
  source_key,
  location,
  category,
  title,
  start_date,
  end_date,
  time_text,
  venue,
  description,
  price,
  registration,
  source_url
) as (
  values
    (
      'saastal-2026-world-cup-public-viewing-saas-grund',
      'Saas-Grund',
      'event',
      'World Cup Public Viewing 2026',
      '2026-06-13'::date,
      '2026-07-19'::date,
      '21:00 for listed Switzerland matches',
      'Open-air theatre, Old Village, Saas-Grund',
      'Watch FIFA World Cup 2026 matches with other football fans. Switzerland matches listed by the destination: 13 June Qatar vs Switzerland, 18 June Switzerland vs Bosnia and Herzegovina, 24 June Switzerland vs Canada.',
      null,
      null,
      'https://www.saas-fee.ch/en/events/weekly-program'
    ),
    (
      'saas-fee-2026-water-channel-beer-hike',
      'Saas-Fee',
      'event',
      'Water channel beer hike',
      '2026-06-20'::date,
      '2026-06-20'::date,
      null,
      'Saas-Fee',
      'A themed hike connected with the historic Saas-Fee water channels and local beer experience.',
      null,
      null,
      'https://www.saas-fee.ch/en/events/top-events-in-summer'
    ),
    (
      'saas-almagell-2026-summer-concert-mattmark-music-society',
      'Saas-Almagell',
      'event',
      'Summer concert: Mattmark Music Society',
      '2026-06-24'::date,
      '2026-06-24'::date,
      '20:30',
      'Village square, Saas-Almagell',
      'Free summer concert in Saas-Almagell by the Mattmark Music Society.',
      'Free of charge',
      'No registration required',
      'https://www.saas-fee.ch/en/events/weekly-program'
    ),
    (
      'saastal-2026-saasfeestival',
      'Saas Valley',
      'event',
      'SaasFeestival',
      '2026-07-12'::date,
      '2026-08-14'::date,
      '12 July - 14 August 2026',
      'Saas Valley',
      'Open-air music festival series in the Saas Valley with seven musical highlights. Good recommendation for guests who ask for music, culture, families or a festive summer atmosphere.',
      'Free entry to all concerts',
      null,
      'https://www.saasfeestival.ch/'
    ),
    (
      'saas-grund-2026-saasfeestival-family-day-kreuzboden',
      'Saas-Grund',
      'event',
      'SaasFeestival Family Day with Plankton',
      '2026-07-12'::date,
      '2026-07-12'::date,
      'from 10:30',
      'Kreuzboden, Saas-Grund',
      'Family Day in the mountains with activities such as fishing, biking, soap bubbles and face painting, plus live music by Plankton. Best recommendation for families with children.',
      'Free entry',
      null,
      'https://www.saasfeestival.ch/'
    ),
    (
      'saas-fee-2026-saasfeestival-two-romans-joya-marleen',
      'Saas-Fee',
      'event',
      'SaasFeestival: The Two Romans and Joya Marleen',
      '2026-07-17'::date,
      '2026-07-17'::date,
      'The Two Romans from 18:30, Joya Marleen from 20:30',
      'Dorfplatz Saas-Fee',
      'Open-air concert evening in Saas-Fee. The Two Romans open with emotional pop songs, followed by Joya Marleen on the main stage.',
      'Free entry',
      null,
      'https://www.saasfeestival.ch/'
    ),
    (
      'saas-fee-2026-saasfeestival-shenanygans-lovebugs',
      'Saas-Fee',
      'event',
      'SaasFeestival: Shenanygans and Lovebugs',
      '2026-07-24'::date,
      '2026-07-24'::date,
      'Shenanygans from 18:30, Lovebugs from 20:30',
      'Dorfplatz Saas-Fee',
      'Open-air concert evening in Saas-Fee. Shenanygans bring energetic indie rock, followed by Lovebugs, one of Switzerland''s best-known bands.',
      'Free entry',
      null,
      'https://www.saasfeestival.ch/'
    ),
    (
      'saas-almagell-2026-saasfeestival-heimatliebi-fruende',
      'Saas-Almagell',
      'event',
      'SaasFeestival: Heimatliebi and Fründe',
      '2026-08-14'::date,
      '2026-08-14'::date,
      'Heimatliebi from 18:30, Fründe from 20:30',
      'Dorfplatz Saas-Almagell',
      'Open-air concert evening in Saas-Almagell with Heimatliebi and Fründe. Good recommendation for guests who want a lively final festival evening in the valley. Extra buses are scheduled after the concert toward Saas-Grund and Saas-Fee.',
      'Free entry',
      null,
      'https://www.saasfeestival.ch/'
    ),
    (
      'saastal-2026-swiss-national-day',
      'Saas Valley',
      'event',
      'Swiss National Day',
      '2026-08-01'::date,
      '2026-08-01'::date,
      null,
      'Saas Valley',
      'Swiss National Day celebrations in the Saas Valley. A strong recommendation for guests staying on 1 August who want a local celebration.',
      null,
      null,
      'https://www.saas-fee.ch/en/events/top-events-in-summer'
    ),
    (
      'saas-fee-2026-nostalgic-culinary-mile',
      'Saas-Fee',
      'event',
      'Nostalgic Culinary Mile',
      '2026-09-06'::date,
      '2026-09-06'::date,
      null,
      'Saas-Fee',
      'A culinary event in Saas-Fee with a nostalgic local atmosphere. Good for guests interested in food, village culture and walking between tasting stops.',
      null,
      null,
      'https://www.saas-fee.ch/en/events/top-events-in-summer'
    ),
    (
      'saas-almagell-2026-mattmark-memorial',
      'Saas-Almagell',
      'event',
      'Mattmark Memorial 45K / 35K / 21K / 8K',
      '2026-09-12'::date,
      '2026-09-12'::date,
      null,
      'Mattmark, Saas-Almagell',
      'Trail-running and running event around the Mattmark area with distances 45K, 35K, 21K and 8K. Best for sporty guests or spectators who want an alpine race atmosphere.',
      null,
      null,
      'https://www.saas-fee.ch/en/events/top-events-in-summer'
    ),
    (
      'saas-fee-2026-autumn-festival',
      'Saas-Fee',
      'event',
      'Autumn Festival',
      '2026-10-02'::date,
      '2026-10-04'::date,
      null,
      'Saas-Fee',
      'Autumn festival weekend in Saas-Fee. Recommend it for guests who want local atmosphere, seasonal food, culture and village life.',
      null,
      null,
      'https://www.saas-fee.ch/en/events/top-events-in-summer'
    ),
    (
      'saas-fee-weekly-water-channel-hike-2026',
      'Saas-Fee',
      'weekly_activity',
      'Water channel hike',
      '2026-06-15'::date,
      '2026-10-31'::date,
      'Monday, registration until 12:00',
      'Village square in front of the church, Saas-Fee',
      'Guided walk along the Lower Water irrigation channel with stories about the culture and history of the water channels.',
      'Free of charge',
      'Registration until 12:00; minimum 6 people; Team Events & Animation, +41 27 958 18 78, animation@saas-fee.ch',
      'https://www.saas-fee.ch/en/events/weekly-program'
    ),
    (
      'saas-fee-weekly-village-tour-2026',
      'Saas-Fee',
      'weekly_activity',
      'Village tour Saas-Fee',
      '2026-06-16'::date,
      '2026-10-31'::date,
      'Tuesday 17:00',
      'Saaser Museum, Saas-Fee',
      'One-hour guided tour about Saas Valley history, traditions, development and tourist attractions.',
      'CHF 12, with SaastalCard CHF 10 including aperitif',
      'Registration until 12:00; Damian Bumann, +41 79 220 28 53, damian@damitas.ch',
      'https://www.saas-fee.ch/en/events/weekly-program'
    ),
    (
      'saas-grund-weekly-past-tour-2026',
      'Saas-Grund',
      'weekly_activity',
      'Exciting journey into the Saas Valley past',
      '2026-06-15'::date,
      '2026-10-31'::date,
      'Monday 17:00',
      'Village square, Saas-Grund',
      'Village tour with tourism pastor, author and blogger Christoph Gysel, focused on the history, culture and tourism of the Saas Valley.',
      'CHF 12, with SaastalCard CHF 10 including aperitif',
      'Registration until 12:00; in German on request from at least 4 persons; Christoph Gysel, +41 79 412 75 18, christoph.gysel@tourismuspfarrer.ch',
      'https://www.saas-fee.ch/en/events/weekly-program'
    ),
    (
      'saas-grund-weekly-legend-evening-2026',
      'Saas-Grund',
      'weekly_activity',
      'Legend evening',
      '2026-06-18'::date,
      '2026-10-31'::date,
      'Thursday 20:00',
      'Saaserstübli, Saas-Grund',
      'An evening of Walser legends in a rustic Saaserstübli atmosphere.',
      'CHF 12, with SaastalCard CHF 8 including aperitif',
      'Registration until 12:00; in German; Christoph Gysel, +41 79 412 75 18, christoph.gysel@tourismuspfarrer.ch',
      'https://www.saas-fee.ch/en/events/weekly-program'
    ),
    (
      'saas-almagell-mattmark-husky-trekking-2026',
      'Saas-Almagell',
      'activity',
      'Husky trekking at Mattmark',
      '2026-06-17'::date,
      '2026-10-31'::date,
      'On request',
      'Mattmark reservoir car park, Saas-Almagell',
      'Guided husky trekking tour around the Mattmark reservoir with mountain views. Good hiking shoes and weather-appropriate clothing are needed.',
      'Adult CHF 180, young person CHF 160, children under 14 without their own husky CHF 30',
      'Wild Swiss Adventure & Dog School GmbH, +41 27 510 48 01, anehrenheim@wild-swiss-adventure.ch',
      'https://www.saas-fee.ch/en/events/weekly-program'
    ),
    (
      'saas-grund-hohsaas-husky-trekking-2026',
      'Saas-Grund',
      'activity',
      'Husky trekking Hohsaas',
      '2026-06-17'::date,
      '2026-10-31'::date,
      'On request',
      'Hohsaas cable car valley station, Saas-Grund',
      'Guided husky trekking tour from Kreuzboden to Hohsaas with mountain views and refreshments included.',
      'Adult CHF 280, young person CHF 260, children under 14 without their own husky CHF 60',
      'Wild Swiss Adventure & Dog School GmbH, +41 27 510 48 01, anehrenheim@wild-swiss-adventure.ch',
      'https://www.saas-fee.ch/en/events/weekly-program'
    ),
    (
      'saas-fee-hannig-cheese-making-2026',
      'Saas-Fee',
      'activity',
      'Cheese making on the Hannig Alp',
      '2026-06-17'::date,
      '2026-10-31'::date,
      'Wednesday 09:15',
      'Alpe Hannig, lower hut, Saas-Fee',
      'Watch the alp team making goat cheese over a wood fire and learn about life on the alp.',
      'Adults CHF 24, with SaastalCard CHF 22; children CHF 8, with SaastalCard CHF 7',
      'Registration by 19:00 the evening before; Alpe Hannig, +41 79 422 34 23',
      'https://www.saas-fee.ch/en/events/weekly-program'
    ),
    (
      'saas-fee-capra-wine-cellar-experience-2026',
      'Saas-Fee',
      'activity',
      'Exclusive wine cellar experience at The Capra',
      '2026-06-11'::date,
      '2026-10-31'::date,
      'Daily on request',
      'The Capra Hotel, Saas-Fee',
      'Culinary wine cellar experience with Valais delicacies and paired Valais wines.',
      'CHF 120 per person',
      'Minimum 6 people; registration deadline 24 hours before; The Capra Hotel, +41 27 958 13 58, welcome@capra.ch',
      'https://www.saas-fee.ch/en/events/weekly-program'
    ),
    (
      'saas-fee-karaoke-barn-2026',
      'Saas-Fee',
      'activity',
      'Karaoke Barn',
      '2026-06-11'::date,
      '2026-10-31'::date,
      'Daily on request, slots 14:00-15:30 or 16:00-17:30',
      'Stadel at Postplatz, Saas-Fee',
      'Private karaoke experience in a cosy Alpine barn atmosphere for friends, family or groups.',
      'CHF 80 per slot',
      'Max. 20 people; key collected from Saas-Fee tourist office with ID; Saastal Tourismus AG, +41 27 958 18 58, info@saas-fee.ch',
      'https://www.saas-fee.ch/en/events/weekly-program'
    )
)
insert into public.local_events (
  source_key,
  location,
  category,
  title,
  start_date,
  end_date,
  time_text,
  venue,
  description,
  price,
  registration,
  source_url,
  is_active,
  updated_at
)
select
  source_key,
  location,
  category,
  title,
  start_date,
  coalesce(end_date, start_date),
  time_text,
  venue,
  description,
  price,
  registration,
  source_url,
  true,
  now()
from rows
on conflict (source_key) do update set
  location = excluded.location,
  category = excluded.category,
  title = excluded.title,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  time_text = excluded.time_text,
  venue = excluded.venue,
  description = excluded.description,
  price = excluded.price,
  registration = excluded.registration,
  source_url = excluded.source_url,
  is_active = true,
  updated_at = now();
